/**
 * HTML → PDF rendering via headless Chromium (Playwright).
 *
 * Complements layoutGen.ts: the HTML generated by Pro is rendered to a
 * faithful A4 PDF. Chromium handles all modern CSS (flex/grid, @page, fonts).
 *
 * Images in <img src="file://..."> are loaded from the local disk (product
 * assets). We wait for the network/file load before printing.
 */

import { promises as fs } from 'fs';
import path from 'path';

/**
 * Inlines <img src="file://..."> images (or absolute paths) into base64 data
 * URIs. Necessary because Chromium via setContent() has an about:blank origin
 * that CANNOT load file:// (security). The base64 is also portable (works in
 * Docker without path issues). Exported for testing.
 */
export async function inlineFileImages(html: string): Promise<string> {
  const MIME: Record<string, string> = {
    '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
    '.gif': 'image/gif', '.webp': 'image/webp', '.svg': 'image/svg+xml',
  };
  // Capture src="file:///abs/x.png" | src="/abs/x.png" | src='file://...'
  const re = /(<img[^>]*\ssrc=)(["'])(file:\/\/)?(\/[^"']+?)(\2)/gi;
  const matches = [...html.matchAll(re)];
  let out = html;
  for (const m of matches) {
    const filePath = m[4];
    const ext = path.extname(filePath).toLowerCase();
    const mime = MIME[ext];
    if (!mime) continue;
    try {
      const data = await fs.readFile(filePath);
      const dataUri = `data:${mime};base64,${data.toString('base64')}`;
      out = out.replace(m[0], `${m[1]}${m[2]}${dataUri}${m[5]}`);
    } catch {
      // missing image: we leave the src as-is (placeholder)
    }
  }
  return out;
}

export interface HtmlToPdfOptions {
  /** Complete HTML (with <style>). */
  html: string;
  /** Output path of the PDF. */
  outPdfPath: string;
  /** Format. Default A4. */
  format?: 'A4' | 'Letter';
  /** Render timeout in ms. Default 30s. */
  timeoutMs?: number;
  /** Print the background colors (print-color-adjust). Default true. */
  printBackground?: boolean;
}

export interface HtmlToPdfResult {
  ok: boolean;
  outPdfPath?: string;
  bytes?: number;
  /** Number of physical pages in the rendered PDF (1 expected; >1 = overflow). */
  pageCount?: number;
  error?: string;
  durationMs: number;
}

/**
 * Renders an HTML to PDF. Best-effort: returns ok:false rather than throwing.
 */
export async function htmlToPdf(opts: HtmlToPdfOptions): Promise<HtmlToPdfResult> {
  const t0 = Date.now();
  let browser: import('playwright').Browser | null = null;
  try {
    // Dynamic import: avoids loading Playwright (heavy) if unused.
    const { chromium } = await import('playwright');
    browser = await chromium.launch({ headless: true });
    const page = await browser.newPage();
    // Inline the file:// images as base64 (setContent doesn't load file://).
    const html = await inlineFileImages(opts.html);
    await page.setContent(html, {
      waitUntil: 'networkidle',
      timeout: opts.timeoutMs ?? 30_000,
    });
    await fs.mkdir(path.dirname(opts.outPdfPath), { recursive: true });
    await page.pdf({
      path: opts.outPdfPath,
      format: opts.format ?? 'A4',
      printBackground: opts.printBackground ?? true,
      preferCSSPageSize: true,
    });
    await browser.close();
    browser = null;
    const st = await fs.stat(opts.outPdfPath);
    // Count the pages: "/Type /Page" in the PDF (reliable, dependency-free
    // heuristic). >1 = the content overflowed (to fix via the prompt).
    let pageCount: number | undefined;
    try {
      const buf = await fs.readFile(opts.outPdfPath);
      const m = buf.toString('latin1').match(/\/Type\s*\/Page[^s]/g);
      pageCount = m ? m.length : undefined;
    } catch { /* best-effort */ }
    return { ok: true, outPdfPath: opts.outPdfPath, bytes: st.size, pageCount, durationMs: Date.now() - t0 };
  } catch (e) {
    if (browser) {
      try { await browser.close(); } catch { /* ignore */ }
    }
    return { ok: false, error: (e as Error).message, durationMs: Date.now() - t0 };
  }
}
